title: Boat race
hero_image: images/small_banner.png
description: Create a boat-racing game in which you have to avoid obstacles
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - title: Starting the boat
  - title: Smooth out the movement
    completion:
      - engaged
  - title: Crash costumes
  - title: Detect a crash
  - title: Reset after a crash
  - title: Start looking normal
  - title: Winning
  - title: Add a timer
    completion:
      - internal
  - title: Booster arrows
  - title: Speed the boat up
  - title: Make a spinning gate
  - title: Spin the gate
  - title: Challenge
    challenge: true
    completion:
      - external
